version: "3.9"
services:
  ldap:
    image: osixia/openldap:1.5.0
    container_name: openldap
    environment:
      LDAP_ORGANISATION: "Demo Org"
      LDAP_DOMAIN: "demo.local"
      LDAP_ADMIN_PASSWORD: admin
    command: ["--copy-service"]
    ports: ["389:389"]
    volumes:
      - ldap-data:/var/lib/ldap
      - ldap-config:/etc/ldap/slapd.d

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap
      PHPLDAPADMIN_HTTPS: "false"
    ports: ["6443:80"]
    depends_on: [ldap]

volumes:
  ldap-data:
  ldap-config:

