version: "3.9"
services:
  db:
    image: bitnami/postgresql:16
    environment:
      - POSTGRESQL_DATABASE=${POSTGRES_DB}
      - POSTGRESQL_USERNAME=${POSTGRES_USER}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db_data:/bitnami/postgresql
    networks: [lab]

  openldap:
    image: bitnami/openldap:2.6
    environment:
      - LDAP_ROOT=cn=admin,${LDAP_BASE_DN}
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
      - LDAP_ENABLE_TLS=no
      - LDAP_BASE_DN=${LDAP_BASE_DN}
      - LDAP_DOMAIN=${LDAP_DOMAIN}
    volumes:
      - ldap_data:/bitnami/openldap
      - ./ldap/seed.ldif:/docker-entrypoint-initdb.d/seed.ldif:ro
    networks: [lab]

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    environment:
      - PHPLDAPADMIN_HTTPS=false
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
    depends_on: [openldap]
    ports:
      - "8081:80"
    networks: [lab]

  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    command:
      - start
      - --hostname-strict=false
      - --proxy=edge
    depends_on: [db, openldap]
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://db:5432/${POSTGRES_DB}
      - KC_DB_USERNAME=${POSTGRES_USER}
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD}
      - KEYCLOAK_ADMIN=${KC_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KC_ADMIN_PASSWORD}
      - KC_FEATURES=saml
      - KC_IMPORT=/opt/keycloak/data/import/realm-export.json
    volumes:
      - kc_data:/opt/keycloak/data
      - ./keycloak:/opt/keycloak/data/import:ro
    ports:
      - "8080:8080"
    networks: [lab]

  simplesaml:
    image: kristophjunge/test-saml-service-provider
    environment:
      - SIMPLESAMLPHP_SP_BASEURL=http://localhost:8082
    depends_on: [keycloak]
    ports:
      - "8082:80"
    networks: [lab]

networks:
  lab: {}

volumes:
  db_data: {}
  kc_data: {}
  ldap_data: {}
